<a href="https://colab.research.google.com/github/jusgowiturs/DataStructure-using-Python/blob/main/Basic_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
import nltk

In [ ]:
String1 = "Hello world , THis is my first programm. This is second Sentence"

In [ ]:
from nltk import sent_tokenize,word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
print(word_tokenize(String1))

['Hello', 'world', ',', 'THis', 'is', 'my', 'first', 'programm']


In [ ]:
print(sent_tokenize(String1))

['Hello world , THis is my first programm.', 'This is second Sentence']


# Numpy Examples

In [ ]:
import numpy as np
def angle_between(v1, v2):
    dot_pr = v1.dot(v2)
    norms = np.linalg.norm(v1) * np.linalg.norm(v2)
 
    return np.rad2deg(np.arccos(dot_pr / norms))
v = np.array([1, 4])
u = np.array([-4, 1])
print(angle_between(v, u))

90.0


In [ ]:
vec1 = np.array([[[1,2,3,4,5],[10,20,30,40,50],[11,21,31,41,51]]])
vec1

array([[[ 1,  2,  3,  4,  5],
        [10, 20, 30, 40, 50],
        [11, 21, 31, 41, 51]]])

In [ ]:
vec1 = vec1.reshape(1,-1)
vec1.shape

(1, 15)

In [ ]:
print(vec1)
vec1[0,0:10]

[[ 1  2  3  4  5 10 20 30 40 50 11 21 31 41 51]]


array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])